### ISSUE TITLE
If you bundle semver, please transpile it too

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-event-bus#145]
Currently semver breaks  IE11.
So we need to manually add it to the transpile set of babel

Since we're transpiling here too, either we don't at all or we should transpile the dependencies that are problematic :thinking: 
```bas
~/Docker/apps2/viewer% npm ls semver
viewer@1.4.0 /home/admin/Docker/apps2/viewer
├─┬ @nextcloud/auth@1.3.0
│ └─┬ @nextcloud/event-bus@1.2.0
│   └── semver@7.3.2 
```

Thoughts?
cc @nickvergessen @ChristophWurst @juliushaertl @georgehrke

**Comment by skjnldsv** [comment]
I'm also fine not transpiling it at all on any of our libraries and make sure our apps do include it with https://www.npmjs.com/package/babel-loader-exclude-node-modules-except

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/spreed/blob/8c3e50e3600ea1370a83ac9535cab2b16f5c1860/webpack.common.js#L54-L55

**Comment by nickvergessen** [comment]
No thoughts from my side 🤷‍♂️

**Comment by skjnldsv** [comment]
relevant https://github.com/nextcloud/nextcloud-axios/issues/151

**Comment by juliushaertl** [comment]
> I'm also fine not transpiling it at all on any of our libraries and make sure our apps do include it with npmjs.com/package/babel-loader-exclude-node-modules-except

I'd vote for that since otherwise the size will probably pile up if every library is transpiled and this is not the libraries responsibility imo.

**Comment by skjnldsv** [comment]
Yeah, I'm more and more leaning towards this :)
So, set every dependency as external and let it do its thing?

How can we improve our way around dependencies that needs to be transpiled in our end apps? Like semver.
Do we have a list somewhere? So we add it by default to the webpack default config?

**Comment by juliushaertl** [comment]
I guess we could just start of with the ones from server and talk and then just continue to maintain that list in the webpack config.
