### ISSUE TITLE
Reduce bundle size?

### ISSUE THREAD

**Issue by te-online** [nextcloud/nextcloud-event-bus#295]
I'm excited to move away from `window.OC` to the `@ nextcloud` packages in most cases and I recently added `@nextcloud/auth` to one of my Nextcloud apps. 🤓  This package, in turn, requires `@nextcloud/nextcloud-bus`, which unfortunately, seems to have had a considerable effect on bundle size. Right now, it's 13.41 % of the whole app's bundle.

```
/node_modules/@nextcloud/event-bus/dist/index.es.js
██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 13.41 % (113.459 KB)
```

I quickly looked through this repository and I can't see any apparent reason why the code transpiles to more than 100 KB, maybe it is the import of semver? Or maybe it is simply legacy browser-support? Any ideas on how to reduce the size? 😊

**Comment by ChristophWurst** [comment]
That's something to analyze indeed. The package code itself is minimal, I can also only imagine it's one of the deps or the transpilation process.

**Comment by te-online** [comment]
Using a different module to replace the functionality provided by `semver` could be a possible solution.

Something like this?

https://www.npmjs.com/package/semver-regex

I can see that some refactoring would be needed, though, so I'm a bit hesitant... 😩

**Comment by te-online** [comment]
I'm going to leave it at that for now. 🤓 Even though improving speed and reducing bundle-size is an important issue, I have to admit that I won't be able to pick up the refactoring work needed. Sorry!

**Comment by juliushaertl** [comment]
Should be fixed by #481 now, right @vinicius73 ?

**Comment by vinicius73** [comment]
Yes @juliushaertl, we are waiting #490 to be merged to close this issue.
It is one of other steps we are thinking to improve all or packages ecosystem.

**Comment by vinicius73** [comment]
New version published
https://bundlephobia.com/package/@nextcloud/event-bus@3.0.0

The v3 is ~60% smaller than previous version.

We will release new versions of `@nextcloud/axios` and `@nextcloud/auth` soon as possible.

https://github.com/nextcloud/nextcloud-axios/pull/438
https://github.com/nextcloud/nextcloud-auth/pull/408
